version: "3.8"

services:
  web:
    image: rubiano718/flaskapp-web:1.0
    container_name: flask_container
    ports:
      - "5000:5000"
    volumes:
      - ./web:/app
      - web_static:/app/static
    networks:
      - appnet
    restart: unless-stopped

  nodeapp:
    image: rubiano718/flaskapp-nodeapp:1.0
    container_name: node_container
    ports:
      - "3000:3000"
    depends_on:
      - web
    volumes:
      - ./node:/usr/src/app
    networks:
      - appnet
    restart: unless-stopped

volumes:
  web_static: {}

networks:
  appnet:
    driver: bridge
